  apiVersion: spanner.cnrm.cloud.google.com/v1beta1
  kind: spannerinstance
  metadata:
    name: mytest3
    namespace: devtest-shuxian-cai
  spec:
    config: regional-us-west1
    displayName: Lowercase CSync
    numNodes: 1
