  apiVersion: spanner.cnrm.cloud.google.com/v1beta1
  kind: spannerinstance
  metadata:
    name: createdbycsync2
    namespace: devtest-shuxian-cai
  spec:
    config: regional-us-west1
    displayName: Created By Config Sync2
    numNodes: 1
